// TweetsNearMe.Scripts.js
(function($){
Type.registerNamespace('TweetsNearMe.Scripts');TweetsNearMe.Scripts.LocationHelper=function(){}
TweetsNearMe.Scripts.LocationHelper.$0=function(){var $0=TweetsNearMe.Scripts.Utils.getCookieValue('Location');if(String.isNullOrEmpty($0)){TweetsNearMe.Scripts.LocationHelper.$1();TweetsNearMe.Scripts.LocationHelper.$2='0';TweetsNearMe.Scripts.LocationHelper.$3='0';}else{var $1=$0.split('|');TweetsNearMe.Scripts.LocationHelper.$3=$1[0];TweetsNearMe.Scripts.LocationHelper.$2=$1[1];if(TweetsNearMe.Scripts.LocationHelper.$3==='0'||TweetsNearMe.Scripts.LocationHelper.$2==='0'){TweetsNearMe.Scripts.LocationHelper.$1();}}}
TweetsNearMe.Scripts.LocationHelper.$1=function(){try{window.navigator.geolocation.getCurrentPosition(function($p1_0){
TweetsNearMe.Scripts.Utils.writeCookie('Location',$p1_0.coords.latitude.toString()+'|'+$p1_0.coords.longitude.toString(),1);TweetsNearMe.Scripts.LocationHelper.$3=$p1_0.coords.latitude.toString();TweetsNearMe.Scripts.LocationHelper.$2=$p1_0.coords.longitude.toString();});}catch($0){}}
TweetsNearMe.Scripts.LocationHelper.get_longitude=function(){if(String.isNullOrEmpty(TweetsNearMe.Scripts.LocationHelper.$2)){TweetsNearMe.Scripts.LocationHelper.$0();}return TweetsNearMe.Scripts.LocationHelper.$2;}
TweetsNearMe.Scripts.LocationHelper.get_latitude=function(){if(String.isNullOrEmpty(TweetsNearMe.Scripts.LocationHelper.$3)){TweetsNearMe.Scripts.LocationHelper.$0();}return TweetsNearMe.Scripts.LocationHelper.$3;}
TweetsNearMe.Scripts.Utils=function(){}
TweetsNearMe.Scripts.Utils.getCookieValue=function(cookieName){var $0=document.cookie.split(';');var $enum1=ss.IEnumerator.getEnumerator($0);while($enum1.moveNext()){var $1=$enum1.current;if($1.substring(0,$1.indexOf('=')).trim()===cookieName){return $1.substr($1.indexOf('=')+1).trim();}}return '';}
TweetsNearMe.Scripts.Utils.writeCookie=function(name,value,days){var $0='';if(days>0){var $1=new Date();$1.setTime($1.getTime()+(days*24*60*60*1000));$0='; expires='+$1.toUTCString();}document.cookie=name+'='+value+$0+'; path=/';}
TweetsNearMe.Scripts.Tweet=function(){}
TweetsNearMe.Scripts.Tweet.prototype={id:0,fromUser:null,text:null,created_at:null,profileImageUrl:null}
TweetsNearMe.Scripts.TweetsViewModel=function(){}
TweetsNearMe.Scripts.TweetsViewModel.prototype={currentTweets:null,$0:0,$1:function(){while(this.currentTweets().length>0){this.currentTweets.shift();}},refresh:function(){if(this.$0>-1){window.clearTimeout(this.$0);}var $0=-1;if(this.currentTweets().length>0){$0=this.currentTweets()[this.currentTweets().length-1].id;}var $1=String.format('http://search.twitter.com/search.json?callback=?&result_type=recent&q=&geocode={0},{1},{2}mi&rpp=25{3}',TweetsNearMe.Scripts.LocationHelper.get_latitude(),TweetsNearMe.Scripts.LocationHelper.get_longitude(),this.$2(),(($0>-1)?('&since_id='+$0):''));var $2={};$2.dataType='jsonp';$2.success=ss.Delegate.create(this,function($p1_0,$p1_1,$p1_2){
var $1_0=$p1_0.results;for(var $1_1=0;$1_1<$1_0.length;$1_1++){var $1_2=new TweetsNearMe.Scripts.Tweet();$1_2.created_at=$1_0[$1_1].created_at;$1_2.id=$1_0[$1_1].id;$1_2.profileImageUrl=$1_0[$1_1].profileImageUrl;$1_2.text=$1_0[$1_1].text;$1_2.fromUser=$1_0[$1_1].fromUser;this.currentTweets.push($1_2);}this.$0=window.setTimeout(ss.Delegate.create(this,this.refresh),2500);});$2.error=ss.Delegate.create(this,function($p1_0,$p1_1,$p1_2){
this.$0=window.setTimeout(ss.Delegate.create(this,this.refresh),5000);});$.ajax($1,$2);},initViewModel:function(){this.currentTweets=ko.observableArray();this.$0=-1;var $0=TweetsNearMe.Scripts.Utils.getCookieValue('Max-Distance');if(!String.isNullOrEmpty($0)){$('#max-distance-field').val($0);}},$2:function(){var $0=parseInt($('#max-distance-field').val());TweetsNearMe.Scripts.Utils.writeCookie('Max-Distance',$0.toString(),7);return $0;}}
TweetsNearMe.Scripts.LocationHelper.registerClass('TweetsNearMe.Scripts.LocationHelper');TweetsNearMe.Scripts.Utils.registerClass('TweetsNearMe.Scripts.Utils');TweetsNearMe.Scripts.Tweet.registerClass('TweetsNearMe.Scripts.Tweet');TweetsNearMe.Scripts.TweetsViewModel.registerClass('TweetsNearMe.Scripts.TweetsViewModel');TweetsNearMe.Scripts.LocationHelper.$2='';TweetsNearMe.Scripts.LocationHelper.$3='';})(jQuery);// This script was generated using Script# v0.7.4.0
