// TweetsNearMe.Scripts.js
(function($){
Type.registerNamespace('TweetsNearMe.Scripts');TweetsNearMe.Scripts.LocationHelper=function(){}
TweetsNearMe.Scripts.LocationHelper.$0=function(){var $0=TweetsNearMe.Scripts.Utils.getCookieValue('Location');if(String.isNullOrEmpty($0)){TweetsNearMe.Scripts.LocationHelper.$1();TweetsNearMe.Scripts.LocationHelper.$2='0';TweetsNearMe.Scripts.LocationHelper.$3='0';}else{var $1=$0.split('|');TweetsNearMe.Scripts.LocationHelper.$3=$1[0];TweetsNearMe.Scripts.LocationHelper.$2=$1[1];if(TweetsNearMe.Scripts.LocationHelper.$3==='0'||TweetsNearMe.Scripts.LocationHelper.$2==='0'){TweetsNearMe.Scripts.LocationHelper.$1();}}}
TweetsNearMe.Scripts.LocationHelper.$1=function(){try{window.navigator.geolocation.getCurrentPosition(function($p1_0){
TweetsNearMe.Scripts.Utils.writeCookie('Location',$p1_0.coords.latitude.toString()+'|'+$p1_0.coords.longitude.toString(),1);TweetsNearMe.Scripts.LocationHelper.$3=$p1_0.coords.latitude.toString();TweetsNearMe.Scripts.LocationHelper.$2=$p1_0.coords.longitude.toString();});}catch($0){}}
TweetsNearMe.Scripts.LocationHelper.get_longitude=function(){if(String.isNullOrEmpty(TweetsNearMe.Scripts.LocationHelper.$2)){TweetsNearMe.Scripts.LocationHelper.$0();}return TweetsNearMe.Scripts.LocationHelper.$2;}
TweetsNearMe.Scripts.LocationHelper.get_latitude=function(){if(String.isNullOrEmpty(TweetsNearMe.Scripts.LocationHelper.$3)){TweetsNearMe.Scripts.LocationHelper.$0();}return TweetsNearMe.Scripts.LocationHelper.$3;}
TweetsNearMe.Scripts.Utils=function(){}
TweetsNearMe.Scripts.Utils.getCookieValue=function(cookieName){var $0=document.cookie.split(';');var $enum1=ss.IEnumerator.getEnumerator($0);while($enum1.moveNext()){var $1=$enum1.current;if($1.substring(0,$1.indexOf('=')).trim()===cookieName){return $1.substr($1.indexOf('=')+1).trim();}}return '';}
TweetsNearMe.Scripts.Utils.writeCookie=function(name,value,days){var $0='';if(days>0){var $1=new Date();$1.setTime($1.getTime()+(days*24*60*60*1000));$0='; expires='+$1.toUTCString();}document.cookie=name+'='+value+$0+'; path=/';}
TweetsNearMe.Scripts.Utils.getLanguage=function(){try{if(!ss.isNullOrUndefined(window.navigator.browserLanguage)){return window.navigator.browserLanguage.substr(0,2).toLowerCase();}}catch($0){}try{if(!ss.isNullOrUndefined(window.navigator.systemLanguage)){return window.navigator.systemLanguage.substr(0,2).toLowerCase();}}catch($1){}try{if(!ss.isNullOrUndefined(window.navigator.userLanguage)){return window.navigator.userLanguage.substr(0,2).toLowerCase();}}catch($2){}return 'en';}
TweetsNearMe.Scripts.Tweet=function(){}
TweetsNearMe.Scripts.Tweet.prototype={id:0,fromUser:null,text:null,created_at:null,profileImageUrl:null,shareUrl:null,shareTweet:function(){window.location.assign(this.shareUrl);}}
TweetsNearMe.Scripts.TweetsViewModel=function(){}
TweetsNearMe.Scripts.TweetsViewModel.prototype={currentTweets:null,$0:0,$1:0,clearTweets:function(){while(this.currentTweets().length>0){this.currentTweets.shift();}$('#loading-indicator').show();this.$1=-1;this.refresh();},refresh:function(){if(this.$0>-1){window.clearTimeout(this.$0);}var $0=String.format('http://search.twitter.com/search.json?callback=?&result_type=recent&lang={0}&q=&geocode={1},{2},{3}mi&rpp=25{4}',TweetsNearMe.Scripts.Utils.getLanguage(),TweetsNearMe.Scripts.LocationHelper.get_latitude(),TweetsNearMe.Scripts.LocationHelper.get_longitude(),this.$3(),((this.$1>-1)?('&since_id='+this.$1):''));var $1={};$1.dataType='jsonp';$1.success=ss.Delegate.create(this,function($p1_0,$p1_1,$p1_2){
$('#loading-indicator').hide();var $1_0=$p1_0.results;$1_0.reverse();for(var $1_1=0;$1_1<$1_0.length;$1_1++){var $1_2=new TweetsNearMe.Scripts.Tweet();$1_2.created_at=($1_0[$1_1].created_at).replaceAll(' +0000','');$1_2.id=$1_0[$1_1].id;if($1_2.id>this.$1){this.$1=$1_2.id;}$1_2.profileImageUrl=$1_0[$1_1].profile_image_url;$1_2.text=$1_0[$1_1].text;$1_2.fromUser=$1_0[$1_1].from_user;var $1_3='https://twitter.com/'+$1_2.fromUser+'/status/'+$1_2.id;var $1_4=$1_2.fromUser+"'s Tweet";$1_2.shareUrl='http://www.facebook.com/sharer.php?u='+encodeURIComponent($1_3)+'&t='+encodeURIComponent($1_4);if(this.currentTweets().length>0){if(this.currentTweets()[0].id===$1_2.id){continue;}}this.currentTweets.unshift($1_2);}this.$0=window.setTimeout(ss.Delegate.create(this,this.refresh),2500);});$1.error=ss.Delegate.create(this,function($p1_0,$p1_1,$p1_2){
this.$0=window.setTimeout(ss.Delegate.create(this,this.refresh),5000);});$.ajax($0,$1);},initViewModel:function(){this.currentTweets=ko.observableArray();this.$0=-1;this.$1=-1;var $0=TweetsNearMe.Scripts.Utils.getCookieValue('Max-Distance');if(!String.isNullOrEmpty($0)){$('#max-distance-field').val($0);$('#max-distance-field').trigger('refresh');}$('#max-distance-field').change(ss.Delegate.create(this,this.$2));},$2:function($p0){this.clearTweets();},$3:function(){var $0=parseInt($('#max-distance-field').val());TweetsNearMe.Scripts.Utils.writeCookie('Max-Distance',$0.toString(),7);return $0;}}
TweetsNearMe.Scripts.LocationHelper.registerClass('TweetsNearMe.Scripts.LocationHelper');TweetsNearMe.Scripts.Utils.registerClass('TweetsNearMe.Scripts.Utils');TweetsNearMe.Scripts.Tweet.registerClass('TweetsNearMe.Scripts.Tweet');TweetsNearMe.Scripts.TweetsViewModel.registerClass('TweetsNearMe.Scripts.TweetsViewModel');TweetsNearMe.Scripts.LocationHelper.$2='';TweetsNearMe.Scripts.LocationHelper.$3='';})(jQuery);// This script was generated using Script# v0.7.4.0
